# Generated by Django 5.2.1 on 2025-05-15 14:02

from django.db import migrations, models

def seed_ksb_types(apps, schema_editor):
    KSBType = apps.get_model('core', 'KSBType')
    KSBType.objects.bulk_create([
        KSBType(id=1, name='Knowledge'),
        KSBType(id=2, name='Skill'),
        KSBType(id=3, name='Behaviour'),
    ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KSBType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RunPython(seed_ksb_types),
    ]
