# Generated by Django 5.2.1 on 2025-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ksb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksb',
            name='description',
            field=models.TextField(unique=True),
        ),
    ]
