# Generated by Django 5.2.1 on 2025-05-15 14:46

from django.db import migrations

def seed_ksbs(apps, schema_editor):
    import uuid
    KSB = apps.get_model('core', 'KSB')

    KSB.objects.create(id=uuid.uuid4(), name='K1', description='Continuous Integration - the benefits of frequent merging of code, the creation of build artefacts and ensuring all tests pass, with automation throughout - including common tooling.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K2', description='The principles of distributed Source Control, including how to exploit the features of the tool, such as branching.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K3', description='How to use data ethically and the implications for wider society, with respect to the use of data, automation and artificial intelligence within the context of relevant data protection policy and legislation.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K4', description='The business value of DevOps in terms of Time, Cost, Quality, with an emphasis on building in internal Quality throughout the lifetime of the product.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K5', description='A range of modern security tools and techniques - e.g. threat modelling, vulnerability scanning and dependency checking, with a general awareness of penetration testing - in order to deal with threats and attack vectors within code and across the cyber domain.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K6', description='A range of problem solving techniques appropriate to the task at hand, such as affinity mapping, impact maps, plan-do-check-act/Deming.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K7', description='General purpose programming and infrastructure-as-code.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K8', description='Immutable infrastructure and how it enables continuous refreshing of software, namely the updating of the operating system, container and security patching.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K9', description='Different organisational cultures, the development frameworks utilised and how they can both complement each other and introduce constraints on delivery.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K10', description='How the user experience sits at the heart of modern development practices in terms of strategies to understand diverse user needs, accessibility and how to drive adoption.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K11', description='Monitoring and alerting technologies and an awareness of the insights that can be derived from the infrastructure and applications - collecting logs and metrics, configuring alerting thresholds, firing alerts and visualising data.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K12', description='The persistence/data layer, including which database/storage technologies are appropriate to each platform type and application when considering non-functional and functional needs; e.g. monolith, microservice, read heavy, write heavy, recovery plans.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K13', description='Automation techniques, such as scripting and use of APIs.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K14', description='Test Driven Development and the Test Pyramid. How the practice is underpinned by unit testing, the importance of automation, appropriate use of test doubles and mocking strategies, reducing a reliance on end-to-end testing.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K15', description='The principles and application of Continuous Integration, Continuous Delivery and Continuous Deployment, including the differences between them.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K16', description='How best to secure data; e.g. encryption in transit, encryption at rest and access control lists (ACL).', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K17', description='What an API is, how to find them and interpret the accompanying documentation.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K18', description='Roles within a multidisciplinary team and the interfaces with other areas of an organisation.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K19', description='Different methods of communication and choosing the appropriate one - e.g. face-to-face (synchronous, high bandwidth), instant messaging, email (asynchronous, low bandwidth), visualisations vs. words.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K20', description='Pair/mob programming techniques and when to use each technique.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K21', description='Architecture principles, common patterns and common strategies for translating user needs into both cloud infrastructure and application code.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K22', description='How their occupation fits into the wider digital landscape and any current or future regulatory requirements.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K23', description='The importance of continual improvement within a blameless culture.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K24', description='The difference between Software-as-a-Service (SaaS) v bespoke v enterprise tooling and how to make an informed choice that suits each use case.', ksb_type_id=1)
    KSB.objects.create(id=uuid.uuid4(), name='K25', description='Maintain an awareness of cloud certification requirements.', ksb_type_id=1)

    # Skills
    KSB.objects.create(id=uuid.uuid4(), name='S1', description='Communicate credibly with technical and non-technical people at all levels, using a range of methods; e.g. ‘Show and Tell’ and ‘Demonstrations’.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S2', description='Work within different organisational cultures with both internal and external parties', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S3', description='Translate user needs into deliverable tasks, writing clear, concise and unambiguous user stories that the whole team can understand.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S4', description='Initiate and facilitate knowledge sharing and technical collaboration', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S5', description='Deploy immutable infrastructure', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S6', description='Install, manage and troubleshoot monitoring tools', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S7', description='Navigate and troubleshoot stateful distributed systems, in order to locate issues across the end-to-end service.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S8', description='Work in agile, multi-disciplinary delivery teams, taking a flexible, collaborative and pragmatic approach to delivering tasks.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S9', description='Application of a range of cloud security tools and techniques - e.g. threat modelling, vulnerability scanning, dependency checking, reducing attack surface area - incorporating these tools and techniques into the automated pipeline wherever possible.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S10', description='Assess identified and potential security threats and take appropriate action based on likelihood v impact.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S11', description='Employ a systematic approach to solving problems, using logic and hypotheses / experimentation to identify the source of issues.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S12', description='Automate tasks where it introduces improvements to the efficiency of business processes and reduces waste, considering the effort and cost of automation.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S13', description='Engage in productive pair/mob programming.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S14', description='Write tests and follow Test Driven Development discipline in various different contexts.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S15', description='Release automation and orchestration as part of a Continuous Integration workflow and Continuous Delivery pipeline, automating the delivery of code from source control to the end users.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S16', description='Invest in continuous learning, both your own development and others, ensuring learning activities dovetail with changing job requirements. Keep up with cutting edge.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S17', description='Code in a general purpose programming language.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S18', description='Specify cloud infrastructure in an infrastructure-as-code domain-specific language.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S19', description='Interpret logs and metrics data within the appropriate context to identify issues and make informed decisions.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S20', description='Writing code in such a way that makes merging easier and facilitates branching by abstraction - i.e. feature toggling.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S21', description='Application of lightweight modelling techniques, such as whiteboarding, in order to gain consensus as a team on evolving architecture.', ksb_type_id=2)
    KSB.objects.create(id=uuid.uuid4(), name='S22', description='Incremental refactoring by applying small behaviour-preserving code changes to evolve the architecture.', ksb_type_id=2)

    # Behaviours
    KSB.objects.create(id=uuid.uuid4(), name='B1', description='Exhibits enthusiasm, openness and an aptitude for working as part of a collaborative community; e.g. sharing best practice, pairing with team members, learning from others and engaging in peer review practices.', ksb_type_id=3)
    KSB.objects.create(id=uuid.uuid4(), name='B2', description='Invests time and effort in their own development, recognising that technology evolves at a rapid rate.', ksb_type_id=3)
    KSB.objects.create(id=uuid.uuid4(), name='B3', description="Displays a commitment to the mantra 'You build it, you run it', taking ownership of deployed code and being accountable for its continual improvement, learning from experience and taking collective responsibility when things fail.", ksb_type_id=3)
    KSB.objects.create(id=uuid.uuid4(), name='B4', description='Is inclusive, professional and maintains a blameless culture.', ksb_type_id=3)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ksb_description'),
    ]

    operations = [
        migrations.RunPython(seed_ksbs)
    ]
