# Generated by Django 5.2.1 on 2025-06-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_themes_onto_ksbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksb',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.theme'),
        ),
    ]
