# Generated by Django 5.2.1 on 2025-06-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ksb_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksb',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ksbs', to='core.theme'),
        ),
    ]
