name: Test and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests with SQLite
      env:
        DJANGO_SETTINGS_MODULE: config.settings
      run: |
        python manage.py migrate --noinput
        pytest

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::261219435789:role/github-actions-eb-deploy-role
        aws-region: eu-west-2

    - name: Install EB CLI
      run: pip install awsebcli

    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p "Python 3.11" endgame --region eu-west-2
        eb use Endgame-env
        eb deploy --staged