name: Test and Deploy to AWS Elastic Beanstalk

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_HOST: localhost
      DB_PORT: 5432
      DEBUG: True
      DJANGO_SETTINGS_MODULE: config.settings

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432; do sleep 1; done

    - name: Run Django migrations and tests with PostgreSQL
      run: |
        python manage.py migrate --noinput
        pytest

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::261219435789:role/github-actions-eb-deploy-role
        aws-region: eu-west-2

    - name: Install EB CLI
      run: pip install awsebcli

    - name: Make EB hook executable
      run: chmod +x .platform/hooks/postdeploy/01_run_migrations.sh

    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p "Python 3.11" ksb --region eu-west-2
        eb use Ksb-env
        eb deploy

    - name: Setup SSH access to EB instance
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EB_SSH_KEY }}" > ~/.ssh/endgame-eb
        chmod 600 ~/.ssh/endgame-eb
        echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

#    - name: Run Django migrations on EB instance
#      run: |
#        eb ssh --command 'source /var/app/venv/*/bin/activate && cd /var/app/current && python manage.py migrate'
#
#    - name: Collect static files on EB instance
#      run: |
#        eb ssh --command 'source /var/app/venv/*/bin/activate && cd /var/app/current && python manage.py collectstatic --noinput --clear'