name: Deploy Terraform

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::261219435789:role/github-actions-terraform-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: terraform plan -var="db_password=${{ secrets.RDS_DB_PASSWORD }}"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="db_password=${{ secrets.RDS_DB_PASSWORD }}"
        working-directory: terraform

